main: online.flowerinsnow.interactions.bukkit.Main
name: Interactions
version: ${project.version}
author: flowerinsnow

commands:
  serverteleport:
    aliases:
      - stp
  shout:

permissions:
  interactions.serverteleport:
    default: op
